CC = gcc
CFLAGS = -Wall -pedantic
.PHONY: all

# $@    :    nome del target
# $^    :    dependency list
# $<    :    first name of dependency list



family   :    family.c
	$(CC) $(CFLAGS) $^ -o $@

exe	:
	./family 5